config/routes.rb
Gabysite::Application.routes.draw do
  get "contact/index"
  get "about/index"
  get "welcome/index"

resources :posts
  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 3 }
has_attached_file :photo, :styles => { :small => "150x150#", :medium =>"350x350#", :large =>"620x620#" },
                  :url  => "/assets/products/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
http_basic_authenticate_with name: "name", password: "password", except: [:show]

def index
	@posts = Post.all
end
def new
	@post = Post.new
end
def create
  @post = Post.new(params[:post].permit(:title, :text, :price, :photo))
 
  @post.save
  redirect_to @post
end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])
 
  if @post.update(params[:post].permit(:title, :text, :price, :photo))
    redirect_to @post
  else
    render 'edit'
  end
end

def show
  @post = Post.find(params[:id])
end
 
def destroy
  @post = Post.find(params[:id])
  @post.destroy
 
  redirect_to posts_path
end
 
private
  def post_params
    params.require(:post).permit(:title, :text, :price)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@posts = Post.all
  	
  end

  def show
  @post = Post.find(params[:id])
end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div id="biohead"><center><h1>About Gaby</h1></center>
</div>


<div id="biopic">
<a href="http://tinypic.com?ref=120tu9w" target="_blank"><img src="http://i43.tinypic.com/120tu9w.jpg" width=250></a> <br><br>
</div>

<div id="bio">
I started making jewelry as a hobby 8 years ago, which fortunately for me has turned into a great business! I started Seville Jewelry and beautiful handcrafted jewelry- that expresses who you are and makes a statement. Hopefully it will touch your soul and lift your spirit as much as it does for me when I create!

My pieces are one of a kind and are ready for shipping. If you are looking for something style/color in particular and aren't finding it...contact me.

I hope that you enjoy looking through my shop.
</div>
<br>

app/views/contact/index.html.erb
<div id="contactcont"><center><h1>Contact</h1></center>

Email: <a href="mailto:GabyCrow@hotmail.com">GabyCrow@hotmail.com</a><br>
Phone: (615) 945-0541


<br><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seville Jewelry</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=Prosto+One' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tag %>
  
</head>
<body>
<div id="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div id="header">
				<h1>Seville<br>Jewelry</h1>	
			</div>
		
			<div id="content">
					<%= yield %>
			</div>

		</div>
		
	</div>


<body>


</body>

<footer>
	<div class="row-fluid">
	<div class="span12">
	<div id="footer">
		<%= link_to 'Home', root_path %><br>
		<%= link_to 'About Gaby', about_index_path %><br>
		<%= link_to 'Contact', contact_index_path %>

		<br>
		<a data-pin-do="buttonFollow" href="http://www.pinterest.com/gabycrow/">Pinterest</a>
		<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
	</div>
</div>
</div>
</div>
</footer>
</div>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true }  do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
<p>
  <%= f.label :price %><br>
  <%= f.text_field :price %>
</p>
 
<p>
   <%= f.file_field :photo %>
</p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Price</th>
    <th>Photo</th>
    <th></th>
  </tr>
 
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td><%= number_to_currency(post.price) %></th>
    <td><%= image_tag post.photo(:small) %></td>
    <td><%= link_to 'Show', post_path(post) %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post_path(post),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="bio">

<p>
  
  <h1><%= @post.title %></h1>
</p>
 


<p>
<%= image_tag @post.photo.url(:medium) %>
</p>

<p>
  
  <%= @post.text %>
</p>

<p>
  <strong>Price:</strong>
  <%= @post.price %> (email Gaby at <a href="mailto:GabyCrow@hotmail.com">GabyCrow@hotmail.com</a> if interested in purchasing)
</p>



<%= link_to 'Back', root_path %>


</div>

app/views/welcome/index.html.erb
<% @posts.each do |post| %>

<div id="item"
  
    <ul>
      <li>
          <%= image_tag post.photo(:small) %></li>
          <div id="desc"

    <li><div id="bio"><%= link_to post.title, post %></div></li>
  </ul>
  </div>

</div>


<% end %>